; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;efault_envs = nodemcu-32s
;default_envs = esp32-c3-display
default_envs = seeed_xiao_esp32s3

[common]
    lib_deps =
        https://github.com/tzapu/WiFiManager
        https://github.com/gmag11/NtpClient
        https://github.com/JChristensen/Timezone
        https://github.com/PaulStoffregen/Time
        https://github.com/bblanchon/ArduinoJson
        https://github.com/FastLED/FastLED
        https://github.com/claws/BH1750
        https://github.com/karol-brejna-i/RemoteDebug
        https://github.com/JoaoLopesF/RemoteDebugger
        ; Some nice to have libraries
        olikraus/U8g2


[env:nodemcu-32s]
    platform = espressif32
    board = nodemcu-32s 
    framework = arduino
    board_build.partitions = partitions.csv
    board_build.filesystem = littlefs
    build_flags =
        -DLED_OUTPUT_PIN=2
    lib_deps = ${common.lib_deps}

    ;upload_protocol = esptool
    ;upload_flags =
    ;    --before
    ;    no_reset

    ;upload_speed = 115200
    ;monitor_speed = 115200

    upload_protocol = espota
    upload_port = QlockThreeW32.local
    ;upload_port = 172.22.102.19
    upload_flags = 
        --port=8266
        --auth=admin
   

[env:esp32-c3-display]
    platform = espressif32
    board = seeed_xiao_esp32c3
    framework = arduino

    board_build.mcu = esp32c3
    board_build.f_cpu = 160000000L
    board_build.partitions = partitions.csv
    board_build.filesystem = littlefs
    build_flags =
        -DLED_OUTPUT_PIN=4
    lib_deps = ${common.lib_deps}
    
    upload_protocol = esptool
    upload_speed = 115200
    monitor_speed = 115200



[env:seeed_xiao_esp32s3]
    platform = espressif32
    board = seeed_xiao_esp32s3
    framework = arduino
    board_build.filesystem = littlefs
    build_flags =
        -DLED_OUTPUT_PIN=4
    lib_deps = ${common.lib_deps}

    upload_protocol = esptool
    upload_speed = 460800
    monitor_speed = 115200

    ;upload_protocol = espota
    ;upload_port = QlockThreeW32.local
    ;upload_flags = 
    ;   --port=8266
    ;   --auth=admin