/**
 * zones
 * Loads the timezone list the picker offers.
 *
 * The file is generated by scripts/zones.py and travels in the filesystem
 * image, so this is a request to the clock itself and works on a network with
 * no internet at all. It is fetched when the timezone tab is first opened
 * rather than bundled: at 16 KB it would be a sixth of the JS bundle, paid for
 * on every visit, for a tab most people open once.
 *
 * @author   Franz Kugler / franz _AT_ franz _MINUS_ kugler _DOT_ de
 * @version  2.1
 * @created  16.8.2026
 * @updated  16.8.2026
 */

let loaded = null;

/** `{ tzdata: "2026c", zones: { "Europe/Berlin": "CET-1CEST,..." } }` */
export async function loadZones() {
  if (loaded) return loaded;

  const res = await fetch('/zones.json');
  if (!res.ok) throw new Error(`/zones.json: HTTP ${res.status}`);

  loaded = await res.json();
  return loaded;
}
