# -*- coding: utf-8 -*-
"""The colour/output model, tested against the firmware it has to agree with.

Every number here is either copied from a source file in this repository or
generated by the pinned FastLED itself (`tests/golden/`). Nothing is an
ordinary HSV conversion: the clock writes `CRGB(CHSV(...))`, which is FastLED's
*rainbow* wheel, and a geometric HSV would be wrong in a way that looks right.
"""
import json
import os
import sys
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "scripts"))

import colour_luminance as cl

with open(os.path.join(HERE, "golden", "fastled_vectors.json"), "r") as handle:
    GOLDEN = json.load(handle)


class GammaTest(unittest.TestCase):
    """`_gammaScale()` in src/LedDriverWS2812FastLED.cpp, copied exactly."""

    def test_documented_checkpoints(self):
        # CLAUDE.md states the curve by three points; they are the cheapest
        # available check that this is the same curve.
        self.assertEqual(cl.gamma_scale(25), 12)
        self.assertEqual(cl.gamma_scale(50), 55)
        self.assertEqual(cl.gamma_scale(75), 135)

    def test_ends_and_floor(self):
        self.assertEqual(cl.gamma_scale(0), 0)
        self.assertEqual(cl.gamma_scale(100), 255)
        self.assertEqual(cl.gamma_scale(101), 255)
        # The floor of 1: without it 1..3 % rounds to zero and the clock goes
        # dark while the web UI says it is on.
        for percent in (1, 2, 3):
            self.assertEqual(cl.gamma_scale(percent), 1)
        # 20 % is a drive of seven, which is the number the coupling notes make
        # a point of: the dim hours live where proportionality is worst.
        self.assertEqual(cl.gamma_scale(20), 7)


# A drive-response record in the shape `scripts/lab.py calibrate` writes and
# `Coupling::parse()` reads: levels descending from 255, each with what it
# gives as a fraction of full. The numbers are the ones this project's notes
# quote for the clock they were measured on - half drive 0.48, a quarter 0.216,
# an eighth 0.082, and 16 giving 0.024 where a proportional lamp would give
# 0.063 - filled out over the levels lab.py actually sweeps.
MEASURED_DRIVE = {
    "drive": {
        "levels":   [255,   192,   128,   96,    64,    48,    32,    24,
                     16,    12,    8,     6,     4],
        "response": [1.0,   0.735, 0.480, 0.352, 0.216, 0.157, 0.100, 0.072,
                     0.024, 0.016, 0.009, 0.006, 0.003],
    },
    "cells": {"7,5": {"r": 67.5, "g": 78.2, "b": 48.2}},
}


class DriveTableTest(unittest.TestCase):
    """`Coupling::responseFor()` and `scripts/lab.py::response()`, same answer.

    The table is not a nicety: 20 % brightness is a drive of seven, so the dim
    hours live entirely where proportionality is 22 % wrong and worse. A model
    that interpolates it differently from the firmware is a different model.
    """

    def setUp(self):
        self.table = cl.DriveTable.from_record(MEASURED_DRIVE)

    def test_matches_the_lab_script_over_every_drive_value(self):
        # Imported rather than transcribed: two copies of an interpolation are
        # two things to keep in step, and this is the one that already exists.
        import lab

        for value in range(0, 256):
            self.assertAlmostEqual(
                self.table.response_for(value), lab.response(MEASURED_DRIVE, value),
                places=9, msg="drive %d" % value)

    def test_the_ends_are_the_firmware_ends(self):
        # Zero is zero, at or above the top measurement is the top reading,
        # and below the lowest measured point it goes straight down to zero
        # rather than flattening out - `Coupling::responseFor()`'s last line.
        self.assertEqual(self.table.response_for(0), 0.0)
        self.assertEqual(self.table.response_for(255), 1.0)
        self.assertEqual(self.table.response_for(255 + 40), 1.0)
        self.assertAlmostEqual(self.table.response_for(2), 0.003 * 2 / 4.0, places=9)

    def test_it_interpolates_between_measured_points(self):
        # Halfway between 128 (0.480) and 96 (0.352).
        self.assertAlmostEqual(self.table.response_for(112), 0.416, places=9)

    def test_a_proportional_table_is_available_and_says_so(self):
        # There has to be something to run the model with before a clock has
        # been calibrated, but it must not pass for a measurement.
        table = cl.DriveTable.proportional()
        self.assertTrue(table.assumed)
        self.assertFalse(self.table.assumed)
        self.assertAlmostEqual(table.response_for(128), 128 / 255.0, places=9)


class DriveTableValidationTest(unittest.TestCase):
    """A malformed table has to be refused, not interpolated.

    `Coupling::responseFor()` walks the levels assuming they descend and that
    the last one is above zero. A table that breaks either assumption does not
    fail - it returns a plausible number, and a plausible wrong number is the
    worst thing a calibration can produce.
    """

    def table(self, levels, response):
        return cl.DriveTable(levels, response)

    def test_the_arrays_must_match_and_hold_something(self):
        with self.assertRaises(ValueError):
            self.table([255, 128], [1.0])
        with self.assertRaises(ValueError):
            self.table([], [])

    def test_the_levels_must_descend_strictly(self):
        with self.assertRaises(ValueError):
            self.table([128, 255], [0.5, 1.0])          # ascending
        with self.assertRaises(ValueError):
            self.table([255, 128, 128], [1.0, 0.5, 0.4])  # a repeat, span zero

    def test_it_refuses_more_levels_than_the_firmware_can_hold(self):
        # COUPLING_MAX_LEVELS is 20 in src/Coupling.h; a longer table would be
        # silently truncated on the clock and the two would disagree.
        self.assertEqual(cl.COUPLING_MAX_LEVELS, 20)
        levels = list(range(255, 255 - 21, -1))
        with self.assertRaises(ValueError):
            self.table(levels, [1.0] * len(levels))

    def test_the_ends_of_the_level_axis_must_be_usable(self):
        with self.assertRaises(ValueError):
            self.table([256, 128], [1.0, 0.5])          # above eight bits
        with self.assertRaises(ValueError):
            self.table([255, 0], [1.0, 0.0])            # last level zero
        with self.assertRaises(ValueError):
            self.table([255, -4], [1.0, 0.0])           # and below

    def test_the_responses_must_be_finite_non_negative_and_lead_somewhere(self):
        with self.assertRaises(ValueError):
            self.table([255, 128], [float("nan"), 0.5])
        with self.assertRaises(ValueError):
            self.table([255, 128], [float("inf"), 0.5])
        with self.assertRaises(ValueError):
            self.table([255, 128], [1.0, -0.5])
        with self.assertRaises(ValueError):
            self.table([255, 128], [0.0, 0.0])          # nothing at full drive

    def test_a_record_without_a_drive_table_is_refused(self):
        with self.assertRaises(ValueError):
            cl.DriveTable.from_record({"cells": {}})

    def test_the_good_table_and_the_fallback_both_pass(self):
        cl.DriveTable.from_record(MEASURED_DRIVE)
        cl.DriveTable.proportional()


class OutputModelTest(unittest.TestCase):
    """`Y(hue, sat, percent)` - relative photopic output of the whole face."""

    def setUp(self):
        self.table = cl.DriveTable.from_record(MEASURED_DRIVE)

    def output(self, hue, sat, percent):
        return cl.relative_photopic_output(hue, sat, percent, drive=self.table)

    def test_white_does_not_depend_on_hue(self):
        # At zero saturation the wheel answers (255, 255, 255) whatever the
        # hue, so every hue must give the same light. The four points this
        # clock has stored were all taught at sat=0, which is what lets them
        # be transformed at all.
        reference = self.output(0, 0, 60)
        for hue in (0, 37, 140, 239, 359):
            self.assertEqual(self.output(hue, 0, 60), reference)

    def test_output_never_falls_as_the_slider_rises(self):
        for hue, sat in ((0, 100), (60, 100), (140, 80), (240, 100), (300, 50), (0, 0)):
            last = -1.0
            for percent in range(0, 101):
                now = self.output(hue, sat, percent)
                self.assertGreaterEqual(now, last, "hue %d sat %d at %d %%" % (hue, sat, percent))
                last = now

    def test_full_blue_is_the_measured_decade_below_green(self):
        # The clock's own measurement: full blue emits about 0.99 decades less
        # than the green it runs, and that number is exactly
        # log10(Y_green / Y_blue) with standard luminance weights. If this
        # drifts, either the weights or the wheel has been changed.
        green = self.output(135, 100, 100)     # hue byte 96 -> (0, 255, 0)
        blue = self.output(225, 100, 100)      # hue byte 160 -> (0, 0, 255)
        self.assertEqual(cl.display_rgb(135, 100), (0, 255, 0))
        self.assertEqual(cl.display_rgb(225, 100), (0, 0, 255))
        self.assertAlmostEqual(cl.log10_output(green) - cl.log10_output(blue), 0.99, places=1)

    def test_white_at_full_is_one(self):
        # The scale is deliberately "relative": white at 100 % is 1, so every
        # other number reads as a fraction of what the face can do.
        self.assertAlmostEqual(self.output(0, 0, 100), 1.0, places=9)

    def test_a_dark_face_has_a_floor_rather_than_a_logarithm_of_zero(self):
        self.assertEqual(self.output(140, 80, 0), 0.0)
        self.assertLess(cl.log10_output(0.0), -6.0)

    def test_weights_are_a_prior_and_are_named_as_one(self):
        self.assertAlmostEqual(sum(cl.PHOTOPIC_WEIGHTS), 1.0, places=6)


class InputValidationTest(unittest.TestCase):
    """Out-of-range inputs are refused where they enter the model.

    Everything downstream is integer arithmetic that wraps: FastLED masks the
    hue to eight bits, so hue 400 is a colour rather than an error, and a
    negative percentage would come out of the gamma as a drive of one. A wrong
    answer that looks like an answer is what this is for.
    """

    def setUp(self):
        self.table = cl.DriveTable.from_record(MEASURED_DRIVE)

    def test_the_weights_must_be_three_finite_non_negative_numbers(self):
        for bad in ([0.5, 0.5], [0.3, 0.3, 0.3, 0.1], [0.2, float("nan"), 0.7],
                    [0.2, float("inf"), 0.7], [0.5, -0.1, 0.6], [0.0, 0.0, 0.0]):
            with self.assertRaises(ValueError, msg=repr(bad)):
                cl.relative_photopic_output(140, 0, 50, weights=bad, drive=self.table)

    def test_hue_saturation_and_percent_are_bounded(self):
        for hue, sat, percent in ((360, 0, 50), (-1, 0, 50), (140, 101, 50),
                                  (140, -1, 50), (140, 0, 101), (140, 0, -1)):
            with self.assertRaises(ValueError, msg="%d/%d/%d" % (hue, sat, percent)):
                cl.relative_photopic_output(hue, sat, percent, drive=self.table)
        # The edges themselves are legal.
        for hue, sat, percent in ((0, 0, 0), (359, 100, 100)):
            cl.relative_photopic_output(hue, sat, percent, drive=self.table)

    def test_the_clock_unit_conversions_are_bounded_too(self):
        with self.assertRaises(ValueError):
            cl.display_rgb(360, 50)
        with self.assertRaises(ValueError):
            cl.display_rgb(140, 101)

    def test_a_point_out_of_range_is_refused_when_it_is_read(self):
        with self.assertRaises(ValueError):
            cl.Point(lux=1.0, percent=120, hue=140, sat=0)
        with self.assertRaises(ValueError):
            cl.Point(lux=1.0, percent=50, hue=400, sat=0)
        with self.assertRaises(ValueError):
            cl.Point(lux=-1.0, percent=50, hue=140, sat=0)
        with self.assertRaises(ValueError):
            cl.Point(lux=float("nan"), percent=50, hue=140, sat=0)
        # HUE_UNKNOWN is not out of range - it is the whole point of it.
        cl.Point(lux=1.0, percent=50, hue=cl.HUE_UNKNOWN, sat=0)

    def test_the_inverse_refuses_a_target_that_is_not_a_number(self):
        for bad in (float("nan"), float("inf"), float("-inf")):
            with self.assertRaises(ValueError):
                cl.percent_for_output(bad, 140, 0, drive=self.table)

    def test_the_inverse_refuses_a_range_it_cannot_search(self):
        with self.assertRaises(ValueError):
            cl.percent_for_output(-1.0, 140, 0, drive=self.table, low=80, high=20)
        with self.assertRaises(ValueError):
            cl.percent_for_output(-1.0, 140, 0, drive=self.table, low=-5, high=100)
        with self.assertRaises(ValueError):
            cl.percent_for_output(-1.0, 140, 0, drive=self.table, low=20, high=120)

    def test_compare_refuses_a_range_that_makes_no_sense(self):
        with self.assertRaises(ValueError):
            cl.compare(SNAPSHOT, drive=self.table, min_percent=80, max_percent=20)


class ShapeValidationTest(unittest.TestCase):
    """Valid JSON is not a valid record, and the difference has to be said.

    `json.load` accepts a list where a mapping belongs, a number where a list
    belongs and a string where a number belongs. Every one of those reached
    arithmetic here and came back as an AttributeError or a TypeError - which
    the command line cannot turn into a message, because it only catches the
    errors this module raises on purpose.
    """

    def test_a_snapshot_has_to_be_a_mapping(self):
        for bad in ([], "a snapshot", 5, None):
            with self.assertRaises(ValueError, msg=repr(bad)):
                cl.points_from_luminance(bad)

    def test_the_points_have_to_be_a_list(self):
        for bad in (5, {"a": 1}, "points", None):
            with self.assertRaises(ValueError, msg=repr(bad)):
                cl.points_from_luminance({"points": bad})
        # An empty list is a shape, not an error - `compare` is what refuses it.
        self.assertEqual(cl.points_from_luminance({"points": []}), [])

    def test_a_point_has_to_be_a_mapping(self):
        for bad in (1, "point", [0.5, 40], None):
            with self.assertRaises(ValueError, msg=repr(bad)):
                cl.points_from_luminance({"points": [bad]})

    def test_a_point_field_has_to_be_a_number(self):
        for field, bad in (("lux", None), ("lux", {}), ("lux", "0.5"),
                           ("percent", None), ("percent", []), ("percent", "40"),
                           ("hue", {}), ("hue", "140"), ("sat", None)):
            entry = {"lux": 1.0, "percent": 50, "hue": 140, "sat": 0}
            entry[field] = bad
            with self.assertRaises(ValueError, msg="%s=%r" % (field, bad)):
                cl.points_from_luminance({"points": [entry]})

    def test_a_coupling_record_has_to_be_a_mapping_all_the_way_down(self):
        for bad in ([], "coupling", 5, None):
            with self.assertRaises(ValueError, msg=repr(bad)):
                cl.DriveTable.from_record(bad)
        for bad in (5, "drive", [255, 128], None):
            with self.assertRaises(ValueError, msg=repr(bad)):
                cl.DriveTable.from_record({"drive": bad})

    def test_the_drive_arrays_have_to_be_arrays(self):
        for levels, response in ((255, 1.0), ("255,128", "1,0.5"),
                                 ({"255": 1.0}, [1.0]), ([255, 128], 1.0)):
            with self.assertRaises(ValueError, msg=repr(levels)):
                cl.DriveTable.from_record({"drive": {"levels": levels,
                                                     "response": response}})

    def test_the_drive_arrays_have_to_hold_numbers(self):
        for levels, response in ((["a", "b"], [1.0, 0.5]),
                                 ([255, None], [1.0, 0.5]),
                                 ([255, 128], ["x", "y"]),
                                 ([255, 128], [1.0, None]),
                                 ([255, [128]], [1.0, 0.5])):
            with self.assertRaises(ValueError, msg=repr((levels, response))):
                cl.DriveTable.from_record({"drive": {"levels": levels,
                                                     "response": response}})


class InverseTest(unittest.TestCase):
    """Discrete, monotonic, and honest about what it cannot reach."""

    def setUp(self):
        self.table = cl.DriveTable.from_record(MEASURED_DRIVE)

    def invert(self, hue, sat, target, **kwargs):
        return cl.percent_for_output(target, hue, sat, drive=self.table, **kwargs)

    def test_forward_then_inverse_returns_the_same_percent(self):
        for hue, sat in ((0, 0), (0, 100), (60, 100), (140, 80), (240, 100), (300, 50)):
            for percent in range(1, 101):
                target = cl.log10_output(
                    cl.relative_photopic_output(hue, sat, percent, drive=self.table))
                found = self.invert(hue, sat, target, low=1, high=100)
                where = "hue %d sat %d wanted %d got %d" % (hue, sat, percent, found.percent)
                # "Nearest feasible" is a statement about light, not about the
                # label on the slider. The gamma sends 1, 2 and 3 % to a drive
                # of one, so those three percentages are the same lamp and the
                # inverse cannot - and should not - tell them apart. What it
                # must do is land on the same emitted output.
                self.assertAlmostEqual(
                    found.log_output,
                    cl.log10_output(
                        cl.relative_photopic_output(hue, sat, percent, drive=self.table)),
                    places=12, msg=where)
                # And where the two percentages really are different lamps, it
                # must be within one point - the quantisation the plan allows.
                same_light = (cl.relative_photopic_output(hue, sat, found.percent, drive=self.table)
                              == cl.relative_photopic_output(hue, sat, percent, drive=self.table))
                self.assertTrue(same_light or abs(found.percent - percent) <= 1, where)
                self.assertIsNone(found.limited, where)

    def test_a_target_above_what_the_colour_can_do_is_reported_not_hidden(self):
        # Deep blue cannot reach a white-equivalent target: about 0.07 of what
        # white emits at the same setting. That is a fact about the gamut and
        # has to surface rather than distort anything.
        white_full = cl.log10_output(
            cl.relative_photopic_output(0, 0, 100, drive=self.table))
        found = self.invert(225, 100, white_full)
        self.assertEqual(found.percent, 100)
        self.assertEqual(found.limited, "ceiling")

    def test_a_target_below_the_range_is_reported_too(self):
        found = self.invert(0, 0, -9.0, low=20, high=100)
        self.assertEqual(found.percent, 20)
        self.assertEqual(found.limited, "floor")

    def test_the_search_respects_the_regulated_range(self):
        target = cl.log10_output(
            cl.relative_photopic_output(0, 0, 5, drive=self.table))
        found = self.invert(0, 0, target, low=20, high=100)
        self.assertEqual(found.percent, 20)
        self.assertEqual(found.limited, "floor")


class HueEndpointTest(unittest.TestCase):
    """0 and 359 degrees are neighbours on the wheel, and stay neighbours."""

    def test_the_ends_of_the_degree_axis_meet(self):
        # The clock's conversion sends 0 to hue byte 0 and 359 to 255, which
        # are adjacent on FastLED's wheel but not identical - 255 is (253,0,2),
        # a red with two counts of blue in it. Both are red, and the light they
        # emit differs by far less than one percentage point of slider.
        self.assertEqual(cl.hue_byte(0), 0)
        self.assertEqual(cl.hue_byte(359), 255)
        table = cl.DriveTable.from_record(MEASURED_DRIVE)
        low = cl.relative_photopic_output(0, 100, 70, drive=table)
        high = cl.relative_photopic_output(359, 100, 70, drive=table)
        self.assertLess(abs(cl.log10_output(low) - cl.log10_output(high)), 0.02)
        # And the inverse agrees within the quantisation, which is the property
        # that matters: turning the wheel past red must not step the brightness.
        target = cl.log10_output(low)
        self.assertLessEqual(
            abs(cl.percent_for_output(target, 0, 100, drive=table).percent
                - cl.percent_for_output(target, 359, 100, drive=table).percent), 1)


# A `GET /luminance` snapshot in the shape src/WebRoutes.cpp builds: the line,
# the range, and every point oldest first. The colour is **absent**, not null,
# on a point taught before the colour was kept - which is the case the reader
# has to handle without guessing red.
SNAPSHOT = {
    "slope": 16.4178, "offset": 57.44, "fitted": True,
    "minPercent": 20, "maxPercent": 100, "capacity": 10, "taught": 4,
    "points": [
        {"used": True,  "lux": 0.0202, "percent": 40,  "seconds": 900, "hue": 140, "sat": 0,  "curve": 33},
        {"used": True,  "lux": 0.0507, "percent": 30,  "seconds": 800, "hue": 140, "sat": 0,  "curve": 39},
        {"used": True,  "lux": 0.6225, "percent": 60,  "seconds": 700, "hue": 140, "sat": 0,  "curve": 57},
        {"used": False, "lux": 9.33,   "percent": 100, "seconds": 600, "hue": 140, "sat": 80, "curve": 100},
    ],
}


class PointTest(unittest.TestCase):
    """Stored points, read and transformed - or refused, and told why."""

    def setUp(self):
        self.table = cl.DriveTable.from_record(MEASURED_DRIVE)

    def test_it_reads_a_luminance_snapshot(self):
        points = cl.points_from_luminance(SNAPSHOT)
        self.assertEqual(len(points), 4)
        self.assertAlmostEqual(points[0].lux, 0.0202)
        self.assertEqual(points[0].percent, 40)
        self.assertEqual(points[0].hue, 140)
        self.assertEqual(points[0].sat, 0)
        # The clock's own verdict travels with the point, under a name that
        # says whose verdict it is - it was made against the clock's range at
        # the time, and this report may be working to a different one.
        self.assertFalse(points[3].reported_used)
        # Censoring is a question about a range, so it takes one.
        self.assertTrue(points[3].at_ceiling(100))
        self.assertFalse(points[3].at_ceiling(120))
        self.assertTrue(points[2].at_ceiling(60))

    def test_a_point_from_before_the_colour_was_kept_is_unknown_not_red(self):
        doc = {"points": [{"lux": 1.0, "percent": 50, "seconds": 10, "used": True}]}
        point = cl.points_from_luminance(doc)[0]
        self.assertEqual(point.hue, cl.HUE_UNKNOWN)
        self.assertFalse(point.colour_known)
        with self.assertRaises(cl.UnknownColourError):
            cl.transform_point(point, drive=self.table)

    def test_an_unknown_point_can_be_transformed_under_a_stated_assumption(self):
        doc = {"points": [{"lux": 1.0, "percent": 50, "seconds": 10, "used": True}]}
        point = cl.points_from_luminance(doc)[0]
        moved = cl.transform_point(point, drive=self.table, assume=(0, 0))
        self.assertTrue(moved.assumed_colour)
        # And it is the same number the assumption would give if it had been
        # stored - the assumption changes provenance, not arithmetic.
        known = cl.Point(lux=1.0, percent=50, hue=0, sat=0, seconds=10)
        self.assertAlmostEqual(moved.z, cl.transform_point(known, drive=self.table).z)

    def test_the_transform_is_log_lux_against_log_output(self):
        point = cl.Point(lux=0.6225, percent=60, hue=140, sat=0, seconds=1)
        moved = cl.transform_point(point, drive=self.table)
        import math
        self.assertAlmostEqual(moved.x, math.log10(0.6225), places=9)
        self.assertAlmostEqual(
            moved.z,
            cl.log10_output(cl.relative_photopic_output(140, 0, 60, drive=self.table)),
            places=9)

    def test_the_lux_floor_is_the_firmware_floor(self):
        # `Luminance::logLux()` floors at LUX_FLOOR (0.01, LightSensor.h) so a
        # dark room is a number rather than minus infinity. A different floor
        # here would move every dark point.
        self.assertAlmostEqual(cl.LUX_FLOOR, 0.01)
        point = cl.Point(lux=0.0, percent=20, hue=0, sat=0, seconds=1)
        self.assertAlmostEqual(cl.transform_point(point, drive=self.table).x, -2.0, places=9)

    def test_a_white_point_transforms_whatever_hue_was_stored_beside_it(self):
        # The four points this clock has were taught at sat=0, so they carry no
        # colour information and can be re-used as they are. That is the whole
        # reason the existing calibration survives this change.
        first = cl.transform_point(
            cl.Point(lux=1.0, percent=45, hue=0, sat=0, seconds=1), drive=self.table)
        second = cl.transform_point(
            cl.Point(lux=1.0, percent=45, hue=300, sat=0, seconds=1), drive=self.table)
        self.assertEqual(first.z, second.z)


class FitTest(unittest.TestCase):
    """`Luminance::fit()` - least squares, both halves, and its three guards."""

    def test_it_reproduces_the_line_the_clock_fitted(self):
        # The three points and the least-squares column CLAUDE.md records for
        # them. The firmware works in float32 through log10f, so the last
        # digit differs; the line does not.
        import math
        points = [cl.Point(lux=0.0202, percent=40, hue=140, sat=0),
                  cl.Point(lux=0.0507, percent=30, hue=140, sat=0),
                  cl.Point(lux=0.6225, percent=60, hue=140, sat=0)]
        xs = [cl.log_lux(p.lux) for p in points]
        line = cl.fit_line(xs, [p.percent for p in points])
        self.assertTrue(line.fitted)
        self.assertAlmostEqual(line.slope, 16.4178, places=1)
        for x, expected in zip(xs, (33.01, 39.56, 57.44)):
            self.assertAlmostEqual(line.at(x), expected, places=1)

    def test_too_little_spread_moves_the_level_and_keeps_the_slope(self):
        # Ten corrections made in one evening say nothing about steepness;
        # least squares through them is noise multiplied by a large number.
        # Below LUM_FIT_MIN_DECADES the slope stands and only the level moves -
        # which is exactly what the old "shift the whole curve" did, done only
        # when it is all one can honestly do.
        self.assertAlmostEqual(cl.LUM_FIT_MIN_DECADES, 0.6)
        xs = [0.0, 0.1, 0.2]
        line = cl.fit_line(xs, [30.0, 55.0, 40.0], keep_slope=25.0)
        self.assertFalse(line.fitted)
        self.assertAlmostEqual(line.slope, 25.0)
        # Through the centroid, whatever the slope turned out to be.
        self.assertAlmostEqual(line.at(0.1), sum([30.0, 55.0, 40.0]) / 3.0, places=6)

    def test_a_slope_of_zero_or_less_is_refused(self):
        # Darker room, brighter clock is not a thing anybody wants, and one
        # careless nudge in daylight produces it.
        line = cl.fit_line([-2.0, 0.0, 1.0], [80.0, 50.0, 20.0], keep_slope=25.0)
        self.assertFalse(line.fitted)
        self.assertAlmostEqual(line.slope, 25.0)

    def test_the_ceiling_is_censored_and_the_floor_is_not(self):
        # The ceiling is what the hardware can do; the floor is a number the
        # owner chose as the dimmest they ever want, so a point sitting on it
        # is a preference being met rather than a wish being cut off.
        points = [cl.Point(lux=0.02, percent=20, hue=0, sat=0),
                  cl.Point(lux=1.0, percent=60, hue=0, sat=0),
                  cl.Point(lux=9.0, percent=100, hue=0, sat=0)]
        used = cl.censor(points, min_percent=20, max_percent=100)
        self.assertEqual(used, [True, True, False])

    def test_censoring_gives_way_rather_than_leaving_nothing_to_fit(self):
        # Two points at the ceiling and nothing else is a poor line, and no
        # line at all is worse.
        points = [cl.Point(lux=1.0, percent=100, hue=0, sat=0),
                  cl.Point(lux=9.0, percent=100, hue=0, sat=0)]
        self.assertEqual(cl.censor(points, 20, 100), [True, True])


class CompareTest(unittest.TestCase):
    """The offline question: is the new coordinate better on the real data?"""

    def setUp(self):
        self.table = cl.DriveTable.from_record(MEASURED_DRIVE)

    def report(self, snapshot=None, **kwargs):
        return cl.compare(snapshot or SNAPSHOT, drive=self.table, **kwargs)

    def test_it_carries_the_optical_stack_it_was_measured_on(self):
        # The stack is part of the photometry: a diffuser in front of the mask
        # rather than behind it is a different device, and a dataset that does
        # not say which one it came from cannot be compared with another.
        self.assertEqual(cl.STACK_ID_DEFAULT, "current-diffuser-before-mask")
        self.assertEqual(self.report()["stackId"], "current-diffuser-before-mask")
        self.assertEqual(self.report(stack_id="mask-then-wh73")["stackId"], "mask-then-wh73")

    def test_it_fits_both_models_on_the_same_points(self):
        report = self.report()
        # The current model, in percent, is what the clock is doing today.
        self.assertAlmostEqual(report["percentFit"]["slope"], 16.4178, places=1)
        # The proposed one, in log relative output. Both fitted from the same
        # three usable points, so the comparison is like for like.
        self.assertTrue(report["outputFit"]["fitted"])
        self.assertEqual(report["percentFit"]["count"], 3)
        self.assertEqual(report["outputFit"]["count"], 3)

    def test_every_point_gets_a_residual_in_both_coordinates(self):
        report = self.report()
        self.assertEqual(len(report["points"]), 4)
        first = report["points"][0]
        self.assertIn("percentResidual", first)     # percentage points
        self.assertIn("outputResidual", first)      # decades
        # And what the new model would have shown at that light, so the two
        # can be compared in the unit the owner actually sees.
        self.assertIn("predictedPercent", first)

    def test_the_ceiling_point_is_censored_in_both_and_says_so(self):
        report = self.report()
        ceiling = report["points"][3]
        self.assertTrue(ceiling["censored"])
        self.assertFalse(ceiling["usedInPercentFit"])
        self.assertFalse(ceiling["usedInOutputFit"])
        self.assertTrue(any("censored" in w for w in report["warnings"]))

    def test_a_ceiling_point_is_censored_even_when_the_snapshot_says_used(self):
        # `used` in a /luminance answer is the *clock's* verdict, made against
        # the clock's own range at the time it was written. This report fits
        # its own lines, possibly over a range given on the command line, so
        # membership has to be recomputed - a stale flag saying "used" must not
        # let a ceiling point into the fit as an equality.
        snapshot = {"minPercent": 20, "maxPercent": 100, "slope": 16.0, "points": [
            {"used": True, "lux": 0.02, "percent": 30, "hue": 140, "sat": 0},
            {"used": True, "lux": 0.60, "percent": 55, "hue": 140, "sat": 0},
            {"used": True, "lux": 9.00, "percent": 100, "hue": 140, "sat": 0},
        ]}
        report = self.report(snapshot)
        ceiling = report["points"][2]
        self.assertTrue(ceiling["censored"])
        self.assertFalse(ceiling["usedInPercentFit"])
        self.assertFalse(ceiling["usedInOutputFit"])
        # And what the clock itself said is kept beside it rather than thrown
        # away: the two disagreeing is worth seeing.
        self.assertTrue(ceiling["clockUsed"])
        self.assertEqual(report["percentFit"]["count"], 2)
        self.assertEqual(report["outputFit"]["count"], 2)

    def test_censoring_follows_the_range_this_report_is_run_with(self):
        # Which points count as censored depends on where the ceiling is, so a
        # range given here rather than by the clock has to move it.
        snapshot = {"minPercent": 20, "maxPercent": 100, "slope": 16.0, "points": [
            {"used": True, "lux": 0.02, "percent": 30, "hue": 140, "sat": 0},
            {"used": True, "lux": 0.60, "percent": 45, "hue": 140, "sat": 0},
            {"used": True, "lux": 9.00, "percent": 60, "hue": 140, "sat": 0},
        ]}
        wide = self.report(snapshot)
        self.assertFalse(wide["points"][2]["censored"])
        narrow = self.report(snapshot, min_percent=20, max_percent=60)
        self.assertTrue(narrow["points"][2]["censored"])
        self.assertFalse(narrow["points"][2]["usedInPercentFit"])
        self.assertEqual(narrow["maxPercent"], 60)

    def test_an_unknown_colour_is_excluded_and_named_rather_than_guessed(self):
        snapshot = {"points": [dict(SNAPSHOT["points"][0]), dict(SNAPSHOT["points"][1]),
                               dict(SNAPSHOT["points"][2]),
                               {"used": True, "lux": 2.0, "percent": 70, "seconds": 5}]}
        report = self.report(snapshot)
        self.assertEqual(report["outputFit"]["count"], 3)
        self.assertEqual(report["percentFit"]["count"], 4)
        self.assertIsNone(report["points"][3]["outputResidual"])
        self.assertTrue(any("unknown colour" in w for w in report["warnings"]))

    def test_an_unknown_point_does_not_censor_a_known_one_out_of_the_fit(self):
        # Censoring and its "fewer than two left" fallback have to be decided
        # over the points that can actually be transformed. Counted over all of
        # them, an unknown point below the ceiling makes the ceiling point look
        # dispensable - and the output fit is then left with one point, or none
        # at all. The two fits have different populations, so they need
        # different censoring passes.
        snapshot = {"minPercent": 20, "maxPercent": 100, "slope": 16.0, "points": [
            {"used": True, "lux": 0.02, "percent": 30, "hue": 140, "sat": 0},
            {"used": True, "lux": 2.00, "percent": 70},               # unknown colour
            {"used": True, "lux": 9.00, "percent": 100, "hue": 140, "sat": 0},
        ]}
        report = self.report(snapshot)
        # The percent fit sees three points, censors the ceiling and keeps two.
        self.assertEqual(report["percentFit"]["count"], 2)
        # The output fit sees only the two it can transform; censoring the
        # ceiling would leave one, so the fallback keeps both - a poor line
        # beats no line, and one point is not a line at all.
        self.assertEqual(report["outputFit"]["count"], 2)
        self.assertTrue(report["outputFit"]["fitted"])

    def test_it_reports_a_residual_offset_per_colour(self):
        # Two points in one colour estimate one offset robustly. That is the
        # whole claim - not a surface over hue and saturation.
        report = self.report()
        white = [g for g in report["colours"] if g["sat"] == 0][0]
        self.assertEqual(white["count"], 3)
        self.assertIn("meanResidual", white)
        self.assertIn("spreadDecades", white)

    NEAR = {"points": [
        {"used": True, "lux": 1.00, "percent": 40, "hue": 140, "sat": 0},
        {"used": True, "lux": 1.30, "percent": 45, "hue": 140, "sat": 0}]}

    def test_without_spread_the_output_fit_is_unavailable_not_invented(self):
        # There is no slope to keep here. The clock's stored slope is in
        # percent per decade and this line is in decades of light per decade of
        # light; dividing one by a hundred is arithmetic, not a conversion, and
        # the number it produces has no source. So: no line, and say so.
        report = self.report(self.NEAR)
        self.assertFalse(report["outputFit"]["available"])
        self.assertIsNone(report["outputFit"].get("slope"))
        self.assertIn("spread", report["outputFit"]["reason"])
        self.assertTrue(any("spread" in w for w in report["warnings"]))
        # Nothing downstream may quietly carry on as if a line existed.
        self.assertEqual(report["curves"], [])
        for row in report["points"]:
            self.assertIsNone(row["outputCurve"])
            self.assertIsNone(row["outputResidual"])
            self.assertIsNone(row["predictedPercent"])
            # What each point emitted is still a fact and still shown.
            self.assertIsNotNone(row["logOutput"])

    def test_a_prior_slope_may_be_supplied_and_is_labelled_as_supplied(self):
        report = self.report(self.NEAR, output_prior_slope=0.42)
        self.assertTrue(report["outputFit"]["available"])
        self.assertFalse(report["outputFit"]["fitted"])
        self.assertTrue(report["outputFit"]["priorSlope"])
        self.assertAlmostEqual(report["outputFit"]["slope"], 0.42)
        self.assertIsNotNone(report["points"][0]["predictedPercent"])

    def test_a_supplied_prior_slope_has_to_be_a_usable_slope(self):
        for bad in (0.0, -0.3, float("nan")):
            with self.assertRaises(ValueError, msg=repr(bad)):
                self.report(self.NEAR, output_prior_slope=bad)

    def test_the_percent_fit_keeps_the_clock_slope_but_invents_none(self):
        # The clock's own slope is a real number and the firmware itself falls
        # back to it, so using it is not an invention - but a snapshot that
        # does not carry one leaves nothing to fall back to.
        with_slope = dict(self.NEAR, slope=16.0)
        report = self.report(with_slope)
        self.assertTrue(report["percentFit"]["available"])
        self.assertFalse(report["percentFit"]["fitted"])
        self.assertAlmostEqual(report["percentFit"]["slope"], 16.0)
        self.assertTrue(report["percentFit"]["priorSlope"])

        bare = self.report(self.NEAR)
        self.assertFalse(bare["percentFit"]["available"])
        self.assertIn("spread", bare["percentFit"]["reason"])

    def test_adequate_spread_still_produces_everything_it_did(self):
        report = self.report()
        self.assertTrue(report["percentFit"]["available"])
        self.assertTrue(report["outputFit"]["available"])
        self.assertTrue(report["outputFit"]["fitted"])
        self.assertFalse(report["outputFit"]["priorSlope"])
        self.assertTrue(report["curves"])
        self.assertIsNotNone(report["points"][0]["predictedPercent"])

    def test_it_predicts_percent_curves_for_the_colours_asked_about(self):
        report = self.report(colours=[(140, 0), (225, 100)])
        curves = {(c["hue"], c["sat"]): c for c in report["curves"]}
        self.assertIn((225, 100), curves)
        blue = curves[(225, 100)]
        # Over the observed lux range, and in the units the slider is in.
        self.assertEqual(len(blue["percent"]), len(blue["lux"]))
        self.assertTrue(all(20 <= p <= 100 for p in blue["percent"]))
        # Deep blue cannot reach a white-equivalent target at the bright end,
        # and that is exposed rather than smoothed away.
        self.assertTrue(any(blue["limited"]))
        self.assertTrue(any("cannot reach" in w for w in report["warnings"]))

    def test_an_assumed_drive_table_is_confessed(self):
        report = cl.compare(SNAPSHOT, drive=cl.DriveTable.proportional())
        self.assertTrue(report["driveAssumed"])
        self.assertTrue(any("drive" in w for w in report["warnings"]))


class CsvAndCliTest(unittest.TestCase):
    """The report as a file, and the command that produces it."""

    def setUp(self):
        import tempfile
        self.table = cl.DriveTable.from_record(MEASURED_DRIVE)
        self.dir = tempfile.mkdtemp()
        self.snapshot = os.path.join(self.dir, "luminance.json")
        self.coupling = os.path.join(self.dir, "coupling.json")
        with open(self.snapshot, "w") as handle:
            json.dump(SNAPSHOT, handle)
        with open(self.coupling, "w") as handle:
            json.dump(MEASURED_DRIVE, handle)

    def tearDown(self):
        import shutil
        shutil.rmtree(self.dir, ignore_errors=True)

    def run_cli(self, *args):
        import contextlib
        import io as string_io
        out = string_io.StringIO()
        with contextlib.redirect_stdout(out):
            code = cl.main(list(args))
        return code, out.getvalue()

    def test_the_csv_is_plain_rows_and_names_the_stack(self):
        import csv
        import io as string_io

        text = cl.report_to_csv(cl.compare(SNAPSHOT, drive=self.table))
        rows = list(csv.reader(string_io.StringIO(text)))
        header = rows[0]
        self.assertEqual(header[0], "kind")
        # Every row carries the stack it was measured on, because a CSV gets
        # separated from its report the moment it is opened in anything.
        self.assertIn("stackId", header)
        kinds = {row[0] for row in rows[1:]}
        self.assertIn("point", kinds)
        self.assertIn("curve", kinds)
        point_rows = [r for r in rows[1:] if r[0] == "point"]
        self.assertEqual(len(point_rows), 4)
        for row in rows[1:]:
            self.assertEqual(row[header.index("stackId")], cl.STACK_ID_DEFAULT)

    def test_the_command_reads_files_and_prints_both_fits(self):
        code, text = self.run_cli("compare", "--luminance", self.snapshot,
                                  "--coupling", self.coupling)
        self.assertEqual(code, 0)
        self.assertIn("percent", text)
        self.assertIn("decades", text)
        self.assertIn(cl.STACK_ID_DEFAULT, text)
        # The censored point has to be visible in the output, not only in the
        # dictionary underneath it.
        self.assertIn("censored", text)

    def test_the_command_writes_the_csv_it_was_asked_for(self):
        target = os.path.join(self.dir, "out.csv")
        code, _ = self.run_cli("compare", "--luminance", self.snapshot,
                               "--coupling", self.coupling, "--csv", target)
        self.assertEqual(code, 0)
        with open(target) as handle:
            self.assertIn("stackId", handle.readline())

    def test_the_command_takes_colours_weights_and_a_stack_id(self):
        code, text = self.run_cli("compare", "--luminance", self.snapshot,
                                  "--coupling", self.coupling,
                                  "--colours", "140/0,225/100",
                                  "--weights", "0.2126,0.7152,0.0722",
                                  "--stack-id", "mask-then-wh73")
        self.assertEqual(code, 0)
        self.assertIn("mask-then-wh73", text)
        self.assertIn("225", text)

    def test_without_a_coupling_file_it_says_the_drive_table_is_a_guess(self):
        code, text = self.run_cli("compare", "--luminance", self.snapshot)
        self.assertEqual(code, 0)
        self.assertIn("assumed proportional", text)

    def fail_cli(self, *args):
        """Run the CLI expecting a refusal; return the message it printed."""
        import contextlib
        import io as string_io
        err = string_io.StringIO()
        with contextlib.redirect_stderr(err), contextlib.redirect_stdout(string_io.StringIO()):
            with self.assertRaises(SystemExit) as caught:
                cl.main(list(args))
        # argparse's own exit code for a usage problem, and its own shape of
        # message. A traceback here would be the script blaming the user for
        # its own lack of an error path.
        self.assertEqual(caught.exception.code, 2)
        text = err.getvalue()
        self.assertNotIn("Traceback", text)
        return text

    def test_a_missing_file_is_an_error_message_not_a_traceback(self):
        text = self.fail_cli("compare", "--luminance",
                             os.path.join(self.dir, "nothing.json"))
        self.assertIn("nothing.json", text)

    def test_malformed_json_is_an_error_message(self):
        broken = os.path.join(self.dir, "broken.json")
        with open(broken, "w") as handle:
            handle.write("{ not json at all ")
        text = self.fail_cli("compare", "--luminance", broken)
        self.assertIn("broken.json", text)

    def test_a_snapshot_the_model_refuses_is_an_error_message(self):
        empty = os.path.join(self.dir, "empty.json")
        with open(empty, "w") as handle:
            json.dump({"points": []}, handle)
        text = self.fail_cli("compare", "--luminance", empty)
        self.assertIn("points", text)

    def test_a_bad_value_on_the_command_line_is_an_error_message(self):
        self.fail_cli("compare", "--luminance", self.snapshot, "--weights", "1,2")
        self.fail_cli("compare", "--luminance", self.snapshot, "--weights", "red,green,blue")
        self.fail_cli("compare", "--luminance", self.snapshot, "--colours", "400/0")
        self.fail_cli("compare", "--luminance", self.snapshot, "--colours", "nonsense")
        self.fail_cli("compare", "--luminance", self.snapshot, "--assume-colour", "140/200")

    def write(self, name, content):
        path = os.path.join(self.dir, name)
        with open(path, "w") as handle:
            json.dump(content, handle)
        return path

    def test_json_of_the_wrong_shape_is_an_error_message_not_a_traceback(self):
        # Each of these parses. None of them is a snapshot.
        for name, content in (("list.json", []),
                              ("string.json", "a snapshot"),
                              ("points-number.json", {"points": 5}),
                              ("points-object.json", {"points": {"a": 1}}),
                              ("entry.json", {"points": [1, 2]}),
                              ("field.json", {"points": [{"lux": None, "percent": 40}]})):
            self.fail_cli("compare", "--luminance", self.write(name, content))

    def test_a_coupling_record_of_the_wrong_shape_is_an_error_message(self):
        for name, content in (("c-list.json", []),
                              ("c-drive.json", {"drive": 5, "cells": {}}),
                              ("c-arrays.json", {"drive": {"levels": 255, "response": 1.0}}),
                              ("c-values.json", {"drive": {"levels": [255, None],
                                                           "response": [1.0, 0.5]}})):
            self.fail_cli("compare", "--luminance", self.snapshot,
                          "--coupling", self.write(name, content))

    def test_a_malformed_coupling_record_is_an_error_message(self):
        broken = os.path.join(self.dir, "coupling-bad.json")
        with open(broken, "w") as handle:
            json.dump({"drive": {"levels": [128, 255], "response": [0.5, 1.0]},
                       "cells": {}}, handle)
        text = self.fail_cli("compare", "--luminance", self.snapshot,
                             "--coupling", broken)
        self.assertIn("descend", text)

    def test_an_unavailable_fit_still_prints_and_still_writes_a_csv(self):
        # A fit that cannot be made is a result the reader has to see. If the
        # report can only render lines that exist, "unavailable" turns into a
        # traceback and the run produces nothing at all.
        near = os.path.join(self.dir, "near.json")
        with open(near, "w") as handle:
            json.dump({"points": [
                {"used": True, "lux": 1.00, "percent": 40, "hue": 140, "sat": 0},
                {"used": True, "lux": 1.30, "percent": 45, "hue": 140, "sat": 0}]}, handle)
        target = os.path.join(self.dir, "near.csv")
        code, text = self.run_cli("compare", "--luminance", near,
                                  "--coupling", self.coupling, "--csv", target)
        self.assertEqual(code, 0)
        self.assertIn("unavailable", text)
        self.assertIn("spread", text)
        # The points themselves are still there, with what each one emitted.
        self.assertIn("1.0000", text)
        with open(target) as handle:
            rows = handle.read().splitlines()
        self.assertEqual(len(rows), 3)          # header and two points, no curve

    def test_the_json_form_round_trips(self):
        code, text = self.run_cli("compare", "--luminance", self.snapshot,
                                  "--coupling", self.coupling, "--json")
        self.assertEqual(code, 0)
        report = json.loads(text)
        self.assertEqual(report["stackId"], cl.STACK_ID_DEFAULT)
        self.assertEqual(len(report["points"]), 4)


class FastLedGoldenTest(unittest.TestCase):
    """Against FastLED 3.9.15 itself, not against a description of it.

    tests/golden/gen_fastled_vectors.cpp compiles the pinned library and prints
    what it answers; if this passes, the Python wheel *is* the clock's wheel.
    """

    def test_rainbow_wheel_matches_every_vector(self):
        for hue, sat, val, red, green, blue in GOLDEN["rainbow"]:
            self.assertEqual(
                cl.hsv2rgb_rainbow(hue, sat, val), (red, green, blue),
                "CHSV(%d, %d, %d)" % (hue, sat, val))

    def test_display_colour_matches_every_vector(self):
        # Through the clock's own 0..359 / 0..100 conversion as well, so the
        # test covers the whole path from what the owner set to what FastLED
        # writes.
        for degrees, percent, red, green, blue in GOLDEN["display"]:
            self.assertEqual(
                cl.display_rgb(degrees, percent), (red, green, blue),
                "hue %d deg, sat %d %%" % (degrees, percent))

    def test_gamma_matches_the_firmware_float_arithmetic(self):
        # The firmware computes this in `float` with `lroundf`; Python is
        # double with round-half-to-even. Over the whole domain they agree,
        # and this is what says so.
        for percent, drive in enumerate(GOLDEN["gamma"]):
            self.assertEqual(cl.gamma_scale(percent), drive, "percent %d" % percent)

    def test_channel_drive_matches_the_driver(self):
        for part, scaled, expected in GOLDEN["channelDrive"]:
            self.assertEqual(cl.channel_drive(part, scaled), expected,
                             "part %d at scale %d" % (part, scaled))

    def test_it_is_not_ordinary_hsv(self):
        # The one vector that would pass with geometric HSV is no test at all.
        # FastLED's rainbow puts "yellow" at (171, 170, 0) where geometric HSV
        # would give (255, 255, 0) - the wheel is deliberately not uniform, and
        # a yellow face is a third of the light an ordinary HSV would predict.
        self.assertEqual(cl.hsv2rgb_rainbow(64, 255, 255), (171, 170, 0))
        # And hue 255 is not hue 0: the wheel does not close on itself.
        self.assertEqual(cl.hsv2rgb_rainbow(255, 255, 255), (253, 0, 2))
        self.assertNotEqual(cl.hsv2rgb_rainbow(255, 255, 255),
                            cl.hsv2rgb_rainbow(0, 255, 255))


if __name__ == "__main__":
    unittest.main()
