include <BOSL2/std.scad>
include <BOSL2/screws.scad>
include <panels.scad>       // generated by scripts/panels.py

size = 250;
pcb_size = 240;
wall = 14;                  
mask_thickness = 3;         // thickness of mask (white PETG)
body_thickness = 24;        // makes a total thickness of 30mm, 3mm diffusor window, 3mm lid and 24mm body.
lid_thickness = 3;          // 3mm to have the same look and feel for front and back
ldx = 1000 / 60;            // LED distance in x
ldy = ldx * 11 / 10;        // calculated for a square panel
lettersize = ldy*4/7;       // calculated letter size (height) - relative to height of cell
grid_thickness = 2;
tol = 0.2;                  // Tolerance

//font="Garamond:style=Bold";
//font="Century Gothic:style=Bold";
font ="";

// The panel to cut, by the code the firmware uses. The letters used to be
// written out here as well, which meant two copies and only one of them
// checked - the clock verifies its own at every boot. See panels.scad for
// what is on offer.
display = panel("de-BA");  //de-BA


module body(){
    difference() {
        union() {
            //masking plate
            difference() {
                cuboid([size,size,mask_thickness], anchor=BOTTOM); 
                //letters
                for(x=[0:10]) for(y=[0:9]) {
                    // we're adjusted to baseline, so calculate offset that the baseline is in the middle of the cell
                    dy = textmetrics("A", lettersize, font=font).size[1] / 2;
                    // now place the correct letter at its place
                    translate([(5-x)*ldx, (4.5-y)*ldy-dy ,-1])
                        linear_extrude(mask_thickness+2)mirror([1,0,0])text(display[y][x], lettersize, font, halign="center", valign="baseline", $fn=64);
                }
                
                //corners
                for(x=[0:1])for(y=[0:1])
                    translate([6*ldx*(2*x-1),5.5*ldy*(2*y-1),-1])cylinder(d=4, h=mask_thickness+2, $fn=32);
                
                // light sensor  
                translate([0,5.5*ldy,-1])cylinder(d=5, h=5);
            }
           
            //frame
            difference(){
                cuboid([size,size,body_thickness], anchor=BOTTOM);
                translate([0,0,-1])cuboid([size-2*wall,size-2*wall,body_thickness+2], anchor=BOTTOM);
                translate([0,0,15])cuboid([pcb_size+1,pcb_size+1,30], anchor=BOTTOM);     // PCB sitting at height 15mm, 3mm mask thickness, 2mm LED height = distance of 10mm.
            }
        }
        // make cutouts for the grid
        translate([0,0,20+1-tol])rotate([180,0,180])grid(grid_thickness+2*tol, 20);
        
        // holes for M3 inserts
        translate([ 120-4, 120-4, 3])cylinder(d=4, h=20, $fn=32);
        translate([ 120-4,-120+4, 3])cylinder(d=4, h=20, $fn=32);
        translate([-120+4, 120-4, 3])cylinder(d=4, h=20, $fn=32);
        translate([-120+4,-120+4, 3])cylinder(d=4, h=20, $fn=32);

        // cutout for USB cable
        translate([0,-size/2+24,17-1.6])cuboid([16,30,30], rounding=2, edges="Y", anchor=BACK+BOTTOM, $fn=64);
        translate([0,(-pcb_size-1)/2,mask_thickness])cuboid([16,30,30], rounding=2,  anchor=FRONT+BOTTOM, $fn=64);
    }
}

module grid(gt,h){
    l=size-2*wall;
    f=2.6;
    difference() {
        union() {
            // grid-fins running up-down
            for(x=[0:13])translate([(6.5-x)*ldx,0,0]){
                if (x==0 || x==13) {
                    cuboid([gt, 12*ldy+grid_thickness, h], anchor=BOTTOM);
                } else {
                    cuboid([gt, l+6, h], anchor=BOTTOM);
            }}
            // grid-fins running left-right
            for(y=[0:12])translate([0,(6-y)*ldy,0]) {
                if (y==0 || y==12) {
                    cuboid([13*ldx+grid_thickness, gt, h], anchor=BOTTOM); 
                } else {
                    cuboid([l+6,gt, h], anchor=BOTTOM);
            }}
            // base plate sitting directly on PCB
            cuboid([13*ldx, 12*ldy, f], anchor=BOTTOM);
            // filled cells to hold the M3 inserts
            for(x=[-6*ldx, 6*ldx])for(y=[-3.5*ldy, 3.5*ldy]){
                translate([x,y,0])cuboid([ldx, ldy, 7], anchor=BOTTOM);
            }    
        }
        // cutout for letter LEDs with capacitors
        for(x=[0:10]) for(y=[0:9]) {
            translate([(5-x)*ldx,   (4.5-y)*ldy ,-1]) cuboid([6.5, 6.5, f+2], anchor=BOTTOM);
            translate([(5-x)*ldx+5, (4.5-y)*ldy ,-1]) cuboid([1.6, 3, 2.6], anchor=BOTTOM);
        }
        // cutout for corner LEDs with capacitors
        for(x=[0:1])for(y=[0:1]) {
            translate([6*ldx*(2*x-1),   5.5*ldy*(2*y-1),-1]) cuboid([6.5, 6.5, f+2], anchor=BOTTOM);
            translate([6*ldx*(2*x-1)+5, 5.5*ldy*(2*y-1),-1]) cuboid([1.6, 3, 2.6], anchor=BOTTOM);
        }
        // cutout for light sensor
        translate([0,5.5*ldy,-1]) cuboid([ldx-grid_thickness, ldy-grid_thickness, f+2], anchor=BOTTOM);

        // cutout for line driver
        translate([4*ldx,-5.5*ldy,-1]) cuboid([ldx-grid_thickness, ldy-grid_thickness, f+2], anchor=BOTTOM);
        
        // cutout for capacitor
        translate([5*ldx,-5.5*ldy,-1]) cuboid([ldx-grid_thickness, ldy-grid_thickness, f+2], anchor=BOTTOM);

        // cutout for USB connector
        translate([0,-6.5*ldy,-1]) cuboid([3*ldx-grid_thickness, 3*ldy-grid_thickness,40]);
        
        // holes for M3 inserts
        for(x=[-6*ldx-3, 6*ldx+3])for(y=[-3.5*ldy, 3.5*ldy]) {
            translate([x,y,-1])cylinder(d=4, h=6, $fn=32);
            echo(160+x,160+y);
        }
    }
}

module lid() {
    difference(){
        union() {
            cuboid([size, size, lid_thickness], anchor=BOTTOM);
            cuboid([pcb_size+1-tol, pcb_size+1-tol, 10], rounding=4, edges="Z", anchor=BOTTOM, $fn=32);

        }
        // mounting screw holes
        for (x=[-120+4, 120-4])for(y=[-120+4, 120-4])translate([x,y,0])rotate([180,0,0])screw_hole("M3", length=10, head="flat", anchor=TOP, $fn=32);

        // make room for the screws holding the grid 
        for(x=[-6*ldx-3, 6*ldx+3])for(y=[-3.5*ldy, 3.5*ldy])translate([x,y,3])cylinder(d=8, h=20, $fn=32);

        // make room for the esp32
        translate([0,-size/2+55,4])cuboid([20,60,20], rounding=2, anchor=BACK+BOTTOM, $fn=64);
        // and the usb cable
        translate([0,-size/2+24,-5])cuboid([16,30,20], rounding=2, anchor=BACK+BOTTOM, $fn=64);
    }

}

module assembly()
{
    // translucent Plate
    color("lightblue", alpha=0.3)cuboid([size,size,3], anchor=TOP);
    // white main body with letters
    color("white")body();
    // black separation grid
    color("black")translate([0,0,1+14])rotate([180,0,180])grid(grid_thickness,2+10+2);
    // PCB with LEDs
    color("lime")translate([0,0,16.6])rotate([180,0,180])import("./stl/board.stl");
    // lid
    color("lightblue")translate([0,0,30-3])rotate([180,0,180])lid();
}

body();