/*
 * The clock's letter panels, generated by scripts/panels.py out of the
 * language files the firmware renders with. Do not edit by hand: a change
 * here would be a panel the clock does not have.
 *
 * Eleven columns by ten rows, row 0 at the top and column 0 on the left,
 * which is how the firmware indexes them too.
 */

// Deutsch, Schwäbisch, Bayrisch, Sächsisch
panel_DE = [
    ["E", "S", "K", "I", "S", "T", "A", "F", "Ü", "N", "F"],
    ["Z", "E", "H", "N", "Z", "W", "A", "N", "Z", "I", "G"],
    ["D", "R", "E", "I", "V", "I", "E", "R", "T", "E", "L"],
    ["V", "O", "R", "F", "U", "N", "K", "N", "A", "C", "H"],
    ["H", "A", "L", "B", "A", "E", "L", "F", "Ü", "N", "F"],
    ["E", "I", "N", "S", "X", "A", "M", "Z", "W", "E", "I"],
    ["D", "R", "E", "I", "A", "U", "J", "V", "I", "E", "R"],
    ["S", "E", "C", "H", "S", "N", "L", "A", "C", "H", "T"],
    ["S", "I", "E", "B", "E", "N", "Z", "W", "Ö", "L", "F"],
    ["Z", "E", "H", "N", "E", "U", "N", "K", "U", "H", "R"]
];

// Schwiizerdütsch
panel_CH = [
    ["E", "S", "K", "I", "S", "C", "H", "A", "F", "Ü", "F"],
    ["V", "I", "E", "R", "T", "U", "B", "F", "Z", "Ä", "Ä"],
    ["Z", "W", "Ä", "N", "Z", "G", "S", "I", "V", "O", "R"],
    ["A", "B", "O", "H", "A", "U", "B", "I", "E", "G", "E"],
    ["E", "I", "S", "Z", "W", "Ö", "I", "S", "D", "R", "Ü"],
    ["V", "I", "E", "R", "I", "F", "Ü", "F", "I", "Q", "T"],
    ["S", "Ä", "C", "H", "S", "I", "S", "I", "B", "N", "I"],
    ["A", "C", "H", "T", "I", "N", "Ü", "N", "I", "E", "L"],
    ["Z", "Ä", "N", "I", "E", "R", "B", "E", "U", "F", "I"],
    ["Z", "W", "Ö", "U", "F", "I", "N", "A", "U", "H", "R"]
];

// English
panel_EN = [
    ["I", "T", "L", "I", "S", "A", "S", "A", "M", "P", "M"],
    ["A", "C", "Q", "U", "A", "R", "T", "E", "R", "D", "C"],
    ["T", "W", "E", "N", "T", "Y", "F", "I", "V", "E", "X"],
    ["H", "A", "L", "F", "S", "T", "E", "N", "F", "T", "O"],
    ["P", "A", "S", "T", "E", "R", "U", "N", "I", "N", "E"],
    ["O", "N", "E", "S", "I", "X", "T", "H", "R", "E", "E"],
    ["F", "O", "U", "R", "F", "I", "V", "E", "T", "W", "O"],
    ["E", "I", "G", "H", "T", "E", "L", "E", "V", "E", "N"],
    ["S", "E", "V", "E", "N", "T", "W", "E", "L", "V", "E"],
    ["T", "E", "N", "S", "E", "O'", "C", "L", "O", "C", "K"]
];

// Français
panel_FR = [
    ["I", "L", "N", "E", "S", "T", "O", "D", "E", "U", "X"],
    ["Q", "U", "A", "T", "R", "E", "T", "R", "O", "I", "S"],
    ["N", "E", "U", "F", "U", "N", "E", "S", "E", "P", "T"],
    ["H", "U", "I", "T", "S", "I", "X", "C", "I", "N", "Q"],
    ["M", "I", "D", "I", "X", "M", "I", "N", "U", "I", "T"],
    ["O", "N", "Z", "E", "R", "H", "E", "U", "R", "E", "S"],
    ["M", "O", "I", "N", "S", "O", "L", "E", "D", "I", "X"],
    ["E", "T", "R", "Q", "U", "A", "R", "T", "P", "M", "D"],
    ["V", "I", "N", "G", "T", "-", "C", "I", "N", "Q", "U"],
    ["E", "T", "S", "D", "E", "M", "I", "E", "P", "A", "M"]
];

// Italiano
panel_IT = [
    ["S", "O", "N", "O", "R", "L", "E", "B", "O", "R", "E"],
    ["È", "R", "L'", "U", "N", "A", "S", "D", "U", "E", "Z"],
    ["T", "R", "E", "O", "T", "T", "O", "N", "O", "V", "E"],
    ["D", "I", "E", "C", "I", "U", "N", "D", "I", "C", "I"],
    ["D", "O", "D", "I", "C", "I", "S", "E", "T", "T", "E"],
    ["Q", "U", "A", "T", "T", "R", "O", "C", "S", "E", "I"],
    ["C", "I", "N", "Q", "U", "E", "S", "M", "E", "N", "O"],
    ["E", "C", "U", "N", "O", "Q", "U", "A", "R", "T", "O"],
    ["V", "E", "N", "T", "I", "C", "I", "N", "Q", "U", "E"],
    ["D", "I", "E", "C", "I", "E", "M", "E", "Z", "Z", "A"]
];

// Nederlands
panel_NL = [
    ["H", "E", "T", "K", "I", "S", "A", "V", "I", "J", "F"],
    ["T", "I", "E", "N", "A", "T", "Z", "V", "O", "O", "R"],
    ["O", "V", "E", "R", "M", "E", "K", "W", "A", "R", "T"],
    ["H", "A", "L", "F", "S", "P", "M", "O", "V", "E", "R"],
    ["V", "O", "O", "R", "T", "H", "G", "É", "É", "N", "S"],
    ["T", "W", "E", "E", "A", "M", "C", "D", "R", "I", "E"],
    ["V", "I", "E", "R", "V", "I", "J", "F", "Z", "E", "S"],
    ["Z", "E", "V", "E", "N", "O", "N", "E", "G", "E", "N"],
    ["A", "C", "H", "T", "T", "I", "E", "N", "E", "L", "F"],
    ["T", "W", "A", "A", "L", "F", "P", "M", "U", "U", "R"]
];

// Español
panel_ES = [
    ["E", "S", "O", "N", "E", "L", "A", "S", "U", "N", "A"],
    ["D", "O", "S", "I", "T", "R", "E", "S", "O", "A", "M"],
    ["C", "U", "A", "T", "R", "O", "C", "I", "N", "C", "O"],
    ["S", "E", "I", "S", "A", "S", "I", "E", "T", "E", "N"],
    ["O", "C", "H", "O", "N", "U", "E", "V", "E", "P", "M"],
    ["L", "A", "D", "I", "E", "Z", "S", "O", "N", "C", "E"],
    ["D", "O", "C", "E", "L", "Y", "M", "E", "N", "O", "S"],
    ["O", "V", "E", "I", "N", "T", "E", "D", "I", "E", "Z"],
    ["V", "E", "I", "N", "T", "I", "C", "I", "N", "C", "O"],
    ["M", "E", "D", "I", "A", "C", "U", "A", "R", "T", "O"]
];

// Every language the firmware knows, in the order of its LANGUAGE_*
// numbers - which are stored in NVS and must keep their values.
panels = [
    ["de-DE", panel_DE],   // Deutsch
    ["de-SW", panel_DE],   // Schwäbisch
    ["de-BA", panel_DE],   // Bayrisch
    ["de-SA", panel_DE],   // Sächsisch
    ["de-CH", panel_CH],   // Schwiizerdütsch
    ["en",    panel_EN],   // English
    ["fr",    panel_FR],   // Français
    ["it",    panel_IT],   // Italiano
    ["nl",    panel_NL],   // Nederlands
    ["es",    panel_ES]   // Español
];

// The letters of one language, e.g. panel("de-DE"). A code that is not
// in the list gives undef, which OpenSCAD complains about loudly enough.
function panel(code) = [for (p = panels) if (p[0] == code) p[1]][0];
