# -*- coding: utf-8 -*-
"""Golden vectors for the cone-plus-harmonic-nose model (FACTORY_SCHEMA 2).

Reads web/public/factory-luminance.json (the file the clock actually loads),
evaluates a spread of cases against a from-scratch Python re-implementation of
FactoryProfile::evaluateWith(), and writes the pair of flat files
tests/host/test_factory_profile.cpp reads with `ifstream >> double`. That
harness has no JSON parser and must not grow one - the point of that file is
that it is pure arithmetic a desktop compiler can take on its own - so this is
the second independent implementation the parity actually rests on, the same
role runtime_vectors()/vectors_flat() played for the grid model this replaced.

    python3 scripts/build_cone_golden_vectors.py
"""
import json
import math
import sys

sys.path.insert(0, "/workspace/scripts")
import colour_luminance as cl

ROOT = "/workspace"
RUNTIME_PATH = ROOT + "/web/public/factory-luminance.json"
OUT_DIR = ROOT + "/tests/golden"

HEAD = '{"checksum":{"algorithm":"sha256","value":"'
MARK = '"},"payload":'


def load_runtime(path):
    text = open(path).read()
    at = len(HEAD) + 64 + len(MARK)
    return json.loads(text[at:-1])


def repr17(value):
    return "%.17g" % float(value)


def blue_weight(payload, hue):
    blue = payload["blue"]
    d = abs(((hue - blue["hue"] + 180) % 360) - 180)
    if d >= blue["blendHalfWidth"]:
        return 0.0
    return 0.5 * (1.0 + math.cos(math.pi * d / blue["blendHalfWidth"]))


def evaluate(payload, lux, hue, sat):
    """A transcription of FactoryProfile::evaluateWith(), independent of
    colour_luminance.percent_for_output() other than sharing the same
    underlying hardware model (rainbow wheel, gamma, drive table) - which is
    exactly the thing being cross-checked, so it is called rather than
    reimplemented a third time."""
    drive = cl.DriveTable(levels=payload["drive"]["levels"],
                          response=payload["drive"]["response"])
    weights = tuple(payload["weights"])
    hue = hue % payload["huePeriod"]

    log_lux = round(math.log10(lux), 10)
    log_lux_min, log_lux_max = payload["cone"]["logLuxMin"], payload["cone"]["logLuxMax"]
    clamped = "below" if log_lux < log_lux_min else "above" if log_lux > log_lux_max else ""

    white = payload["cone"]["slope"] * log_lux + payload["cone"]["offset"]
    nose = (payload["nose"]["a0"]
            + payload["nose"]["a1"] * math.cos(math.radians(hue))
            + payload["nose"]["b1"] * math.sin(math.radians(hue)))
    blue_line = payload["blue"]["slope"] * log_lux + payload["blue"]["offset"]
    w = blue_weight(payload, hue)
    residual = nose + w * (blue_line - nose)

    sat_zero, sat_full = payload["satFade"]["zeroAtSat"], payload["satFade"]["fullAtSat"]
    if sat <= sat_zero:
        fade = 0.0
    elif sat >= sat_full:
        fade = 1.0
    else:
        fade = (sat - sat_zero) / float(sat_full - sat_zero)
    residual *= fade
    if fade == 0.0:
        residual = 0.0

    target = white + residual
    low, high = payload["percentRange"]["min"], payload["percentRange"]["max"]

    best_percent, best_z, best_gap = low, None, None
    lowest = highest = None
    for percent in range(low, high + 1):
        z = cl.log10_output(cl.relative_photopic_output(hue, sat, percent, weights, drive))
        if lowest is None or z < lowest:
            lowest = z
        if highest is None or z > highest:
            highest = z
        gap = abs(z - target)
        if best_z is None or gap < best_gap:
            best_percent, best_z, best_gap = percent, z, gap

    limited = "ceiling" if target > highest else "floor" if target < lowest else ""
    return {"percent": best_percent, "target": target, "limited": limited,
            "clamped": clamped}


LIMITED_CODES = {"": 0, "ceiling": 1, "floor": 2}
CLAMP_CODES = {"": 0, "below": 1, "above": 2}


def profile_flat(payload):
    lines = ["# generated by scripts/build_cone_golden_vectors.py - do not edit",
             "%d %d" % (payload["percentRange"]["min"], payload["percentRange"]["max"]),
             "%d %d" % (payload["satFade"]["zeroAtSat"], payload["satFade"]["fullAtSat"]),
             str(payload["huePeriod"]),
             "%s %s %s %s" % (repr17(payload["cone"]["slope"]), repr17(payload["cone"]["offset"]),
                              repr17(payload["cone"]["logLuxMin"]), repr17(payload["cone"]["logLuxMax"])),
             "%s %s %s" % (repr17(payload["nose"]["a0"]), repr17(payload["nose"]["a1"]),
                          repr17(payload["nose"]["b1"])),
             "%d %s %s %s" % (payload["blue"]["hue"], repr17(payload["blue"]["slope"]),
                             repr17(payload["blue"]["offset"]), repr17(payload["blue"]["blendHalfWidth"]))]
    drive = payload["drive"]
    lines.append(str(len(drive["levels"])))
    lines.append(" ".join(str(one) for one in drive["levels"]))
    lines.append(" ".join(repr17(one) for one in drive["response"]))
    lines.append(" ".join(repr17(one) for one in payload["weights"]))
    return "\n".join(lines) + "\n"


def vectors_flat(cases):
    lines = ["# generated by scripts/build_cone_golden_vectors.py - do not edit",
             str(len(cases))]
    for case in cases:
        lines.append(" ".join([
            repr17(case["lux"]), str(case["hue"]), str(case["sat"]),
            str(case["found"]["percent"]), repr17(case["found"]["target"]),
            str(LIMITED_CODES[case["found"]["limited"]]),
            str(CLAMP_CODES[case["found"]["clamped"]])]))
    return "\n".join(lines) + "\n"


def build():
    payload = load_runtime(RUNTIME_PATH)
    blue_hue = payload["blue"]["hue"]
    half = payload["blue"]["blendHalfWidth"]

    asked = []
    for lux in (0.02, 0.07, 0.15, 0.5, 1.9, 10.0):          # the six real levels
        for hue in (0, 60, 120, 180, 240, 300):
            asked.append((lux, hue, 100))
            asked.append((lux, hue, 0))
    for lux in (0.03, 0.11, 0.4, 4.5):                      # between them
        for hue in (15, 91, 137, 210, 259, 331):
            asked.append((lux, hue, 100))
    # The blend zone around blue: at its centre, at the edge of the window,
    # just inside and just outside - the seam this model has instead of a
    # grid corner.
    for offset in (0, half * 0.3, half * 0.99, half, half * 1.5, 180):
        asked.append((1.9, (blue_hue + int(round(offset))) % 360, 100))
        asked.append((1.9, (blue_hue - int(round(offset))) % 360, 100))
    for hue in (300, 305, 315, 330, 345, 355, 359, 0):      # the hue-360 seam
        asked.append((0.5, hue, 100))
    for sat in (1, 17, 33, 50, 66, 99):                     # down the fade
        asked.append((0.5, 240, sat))
        asked.append((0.5, 60, sat))
    for lux in (0.001, 0.005, 0.019, 10.5, 90.0, 5000.0):   # outside the measured range
        asked.append((lux, 240, 100))
        asked.append((lux, 0, 100))

    cases = []
    for lux, hue, sat in asked:
        cases.append({"lux": lux, "hue": hue, "sat": sat,
                      "found": evaluate(payload, lux, hue, sat)})

    open(OUT_DIR + "/factory_profile.txt", "w").write(profile_flat(payload))
    open(OUT_DIR + "/factory_vectors.txt", "w").write(vectors_flat(cases))
    print("%d cases written to %s" % (len(cases), OUT_DIR))


if __name__ == "__main__":
    build()
